# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/mips_cpu/mips_cpu.cache/wt [current_project]
set_property parent.project_path C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/mips_cpu/mips_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/mips_cpu/mips_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/circuit/ALU_Signal.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/AND_GATE.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/AND_GATE_10_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/AND_GATE_11_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/AND_GATE_12_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/AND_GATE_4_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/AND_GATE_5_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/AND_GATE_6_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/AND_GATE_9_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/arithmetic/Adder.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/wiring/Bit_Extender.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/wiring/Bit_Extender_8_32_SIGN.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/wiring/Bit_Extender_SIGN.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/arithmetic/Comparator.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/circuit/Control.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/circuit/Control_Signal.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/io/Counter.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/io/FPGADigit.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/base/LogisimClockComponent.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/base/LogisimTickGenerator.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/circuit/MIPS_ALU.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/circuit/MIPS_CPU.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/circuit/MIPS_Regifile.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/plexers/Multiplexer_bus_2.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/plexers/Multiplexer_bus_4.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/NOT_GATE.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/OR_GATE.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/OR_GATE_11_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/OR_GATE_14_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/OR_GATE_3_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/OR_GATE_4_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/OR_GATE_5_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/OR_GATE_7_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/gates/OR_GATE_9_INPUTS.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/memory/RAM_RAM.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/memory/REGISTER_FLIP_FLOP.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/memory/REGISTER_FLIP_FLOP_PC.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/memory/ROM_ROM.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/arithmetic/Shifter_32_bit.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/io/decoder3_8.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/io/display_sel.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/io/divider.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/io/sevenseg_dec.v
  C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/verilog/toplevel/LogisimToplevelShell.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/xdc/LogisimToplevelShell.xdc
set_property used_in_implementation false [get_files C:/Users/dell/Desktop/cpu.circ/cpu24toFPGA/MIPS_CPU/xdc/LogisimToplevelShell.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top LogisimToplevelShell -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LogisimToplevelShell.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LogisimToplevelShell_utilization_synth.rpt -pb LogisimToplevelShell_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
